### ISSUE TITLE
out of bounds error before initialization

### ISSUE THREAD

**Issue by felixmxr** [Ultrawipf/OpenFFBoard#48]
recently, at least on my setup, my tmc4671 doesnt initialize() or get to encoder alignment()

i have tracked down the change to line 175 in FFBoard/src/Axis.cpp prepareforUpdate()
previously  `if (!drv->motorReady()) return;` allowed the rest of the function to be skipped over

but now with the line commented out `//if (!drv->motorReady()) return;` the function continues, and asks for a position from the tmc4671 encoder engine. sometimes the encoder engine returns a nonsensical value and the outofbounds error is triggered, which prevents the tmc4671 from ever getting to initialize()

is this intended behavior?
this could be related to my setup (tmc4671-6100 BOB) or the fact that i am using my sincos encoder in single ended mode and the offset is way too far off from the reference 2.5 volts for the tmc4671 to make sense of the reading

**Comment by Ultrawipf** [comment]
Probably a lot of things will not work if the hardware is not replicated completely.
It will check the internal and external voltages (ADC of STM, fed by dividers on TMC driver board) to decide when to activate the driver. That also controls the braking resistor and other errors.

There are some bigger changes planned in the tmc class but you will probably need to at least have all the signals of the original hardware present in order to make it work at the moment.
